#!/bin/sh
set -e

cp engine.c engine.h dev/tests/
sed -i 's/^static//g' dev/tests/engine.c

(
	cd dev/tests/
	cc -o tests tests.c engine.c
	./tests
)

rm -f dev/tests/engine.c dev/tests/engine.h dev/tests/tests
