#!/bin/sh
set -e

command -v pytest >/dev/null 2>&1 || {
    pip install -U pip wheel setuptools
    pip install -U pygame numpy pytest
}

cp ./engine.c ./engine.c.orig
sed -i 's/^static//g' ./engine.c
cc -Wall -O3 -ftree-vectorize -ffast-math -fPIC -fopenmp -c -o ./engine.o ./engine.c
cc ./engine.o -shared -fopenmp -o ./engine.so
mv ./engine.c.orig ./engine.c

pytest tests/tests.py

rm -f ./engine.so ./engine.o
