#!/bin/sh
export DISPLAY=:99

Xvnc "$DISPLAY" -geometry 5120x2880 -depth 24 -rfbport 5900 -SecurityTypes None >"$HOME/.local/xvnc.log" 2>"$HOME/.local/xvnc.err.log" &
/usr/share/novnc/utils/novnc_proxy --vnc localhost:5900 >"$HOME/.local/novnc.log" 2>"$HOME/.local/novnc.err.log" &
wait
