name: Test Life
description: These tests run on one cell per pixel, making them a stress test for the worst-case scenario.

on:
  push:
    branches:
      - main

jobs:
  acceptance:
    runs-on: ubuntu-latest
    container:
      image: debian:bookworm-slim
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          apt-get update
          DEBIAN_FRONTEND=noninteractive apt-get upgrade -y --no-install-recommends \
            gcc \
            libc-dev \
            libx11-dev \
            libxext-dev \
            libxinerama-dev \
            make \
            xvfb
      - name: Build
        run: make DEBUG_FLAGS=-DDEBUG_FPS_LOGGING
      - name: Test
        run: dev/test
