name: Test Life

on:
  push:
    branches:
      - main

jobs:
  acceptance:
    runs-on: ubuntu-latest
    container:
      image: debian:bookworm-slim
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          apt-get update
          DEBIAN_FRONTEND=noninteractive apt-get upgrade -y --no-install-recommends \
          bc \
          gcc \
          libc-dev \
          libglib2.0-0 \
          libglib2.0-dev \
          libpthread-stubs0-dev \
          libx11-dev \
          make \
          xserver-xorg-video-dummy \
          xvfb
      - name: Build
        run: make
      - name: Test
        run: dev/test
