name: Test Life
description: These tests run on one cell per pixel, making them a stress test for the worst-case scenario.

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: debian:bookworm-slim
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          apt-get update
          DEBIAN_FRONTEND=noninteractive apt-get upgrade -y --no-install-recommends \
            gcc \
            libc-dev \
            libx11-dev \
            libxext-dev \
            libxinerama-dev \
            make
      - name: Build
        run: |
          make DEBUG_FLAGS="-DFPS_LOGGING -DUPDATE_CALC_LOGGING -DUPDATE_DRAW_LOGGING"
          tar -cf life.tar life
      - uses: actions/upload-artifact@v4
        with:
          name: life
          path: life.tar
          compression-level: 9
          retention-days: 1

  test:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: debian:bookworm-slim
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          apt-get update
          DEBIAN_FRONTEND=noninteractive apt-get upgrade -y --no-install-recommends python3 xvfb
      - uses: actions/download-artifact@v4
        with:
          name: life
      - name: Extract artifact
        run: tar -xf life.tar
      - name: Test
        run: dev/citest
