name: Test Life

on:
  push:
    branches:
      - main
    

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: python:3-slim
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          DEBIAN_FRONTEND=noninteractive
          apt-get update
          apt-get upgrade -y --no-install-recommends gcc libc-dev libglib2.0-0 libglib2.0-dev libpthread-stubs0-dev libx11-dev make xvfb xserver-xorg-video-dummy bc
          pip install --upgrade pip
          pip install pygame numpy pyinstaller
      - name: Build
        run: make
      - name: Test
        run: dev/test
